###> JUST EXAMPLE, copy it into your config ###

gs_service:
    locale:                     '%env(LOCALE)%'

    timezone:                   '%env(TIMEZONE)%'

    app_env:                    '%env(APP_ENV)%'

    local_drive_for_test:       '%env(LOCAL_DRIVE_FOR_TEST)%'

    load_packs_configs:
        -   pack_name:      'monolog'
            pack_rel_path:  ~
    
    year_regex:         '(?:\b[0-9]{4}\b|\b[0-9]{2}\b)'
    year_regex_full:    '[0-9]{4}'
    ip_v4_regex:        '(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'
    slash_of_ip_regex:  '[/\\]{1,2}'