monolog:

    # Service will be enabled as: monolog.logger.<channel>
    channels:
    
        - gs_command.dev_logger
    
    handlers:

        gs_command.dev_logger:
            type:           rotating_file
            max_files:      1
            path:           "%kernel.logs_dir%/gs_command_%kernel.environment%_debug.log"
            level:          debug
            channels:       ["gs_generic_parts.debug"]