parameters:

services:
    _defaults:
        public:             false
        autowire:           false
        autoconfigure:      false
        
        bind:
            ###> VALUES ###
            # TODO: hard
            $projectDir:                '../../../../%kernel.project_dir%'
            $packageFilenames:          '%gs_service.load_packs_configs%'
            ###< VALUES ###
            
            ###> SERVICES ###
            ###< SERVICES ###
            