parameters:
    ###> BY DEFAULT ###
    gs_service.locale:      'en_US'
    gs_service.timezone:    '+12:00'
    gs_service.year_regex:          '(?:\b[0-9]{4}\b|\b[0-9]{2}\b)'
    gs_service.year_regex_full:     '[0-9]{4}'
    gs_service.ip_v4_regex:         '(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'
    gs_service.slash_of_ip_regex:   '[/\\]{1,2}'
    ###< BY DEFAULT ###

services:
    _defaults:
        public:             false
        autowire:           false
        autoconfigure:      false
        
        bind:
            ###> VALUES ###
            $appEnv:                    '%gs_service.app_env%'
            $projectDir:                '../../../../%kernel.project_dir%'
            $packageFilenames:          '%gs_service.load_packs_configs%'
            
            $yearRegex:                 '%gs_service.year_regex%'
            $yearRegexFull:             '%gs_service.year_regex_full%'
            $ipV4Regex:                 '%gs_service.ip_v4_regex%'
            $slashOfIpRegex:            '%gs_service.slash_of_ip_regex%'
            ###< VALUES ###
            
            ###> SERVICES ###
            
            ###> SYMFONY SERVICES ###
            $slugger:                   '@slugger'
            ###< SYMFONY SERVICES ###
            
            ###> BUNDLE SERVICES (You can use them by @<name> in your services.yaml) ###
            #$faker:                     '@gs_service.faker'
            $carbonFactory:             '@gs_service.carbon_factory'
            ###< BUNDLE SERVICES (You can use them by @<name> in your services.yaml) ###
            
            ###< SERVICES ###