parameters:
    ###> BY DEFAULT ###
    gs_service.locale:      'en_US'
    gs_service.timezone:    '+12:00'
    ###< BY DEFAULT ###

services:
    _defaults:
        public:             false
        autowire:           false
        autoconfigure:      false
        
        bind:
            ###> VALUES ###
            $appEnv:                    '%gs_service.app_env%'
            $projectDir:                '../../../../%kernel.project_dir%'
            $packageFilenames:          '%gs_service.load_packs_configs%'
            ###< VALUES ###
            
            ###> SERVICES ###
            
            ###> SYMFONY SERVICES ###
            $slugger:                   '@slugger'
            ###< SYMFONY SERVICES ###
            
            ###> BUNDLE SERVICES (You can use them by @<name> in your services.yaml) ###
            #$faker:                     '@gs_service.faker'
            $carbonFactory:             '@gs_service.carbon_factory'
            ###< BUNDLE SERVICES (You can use them by @<name> in your services.yaml) ###
            
            ###< SERVICES ###