parameters:

services:
    _defaults:
        public:             false
        autowire:           false
        autoconfigure:      false
        
        bind:
            ###> VALUES ###
            ###< VALUES ###
            
            ###> SERVICES ###
            ###< SERVICES ###
            